#Cargando datos a través de la función `read_csv`

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd

In [ ]:
data1 = pd.read_csv("/content/drive/MyDrive/Machine Learning - Python/Datasets - Machine Learning/titanic/titanic3.csv")

In [ ]:
data1.head()

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
1,1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1,0,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"

Para evitar la sobrecarga de código, podemos guardar la ruta del archivo que se va a leer en una variable, que llamaremos `path1`.

In [ ]:
path1 = "/content/drive/MyDrive/Machine Learning - Python/Datasets - Machine Learning/titanic/titanic3.csv"

In [ ]:
data1 = pd.read_csv(path1)

In [ ]:
data1.head()

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
1,1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1,0,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"

Podemos cargar un documento txt con el método `read_csv`, si la separación viene dada por comas.

In [ ]:
path2 = "/content/drive/MyDrive/Machine Learning - Python/Datasets - Machine Learning/customer-churn-model/Customer Churn Model.txt"

In [ ]:
data2 = pd.read_csv(path2)

In [ ]:
data2.head()

,State,Account Length,Area Code,Phone,Int'l Plan,VMail Plan,VMail Message,Day Mins,Day Calls,Day Charge,...,Eve Calls,Eve Charge,Night Mins,Night Calls,Night Charge,Intl Mins,Intl Calls,Intl Charge,CustServ Calls,Churn?
0,KS,128,415,382-4657,no,yes,25,265.1,110,45.07,...,99,16.78,244.7,91,11.01,10.0,3,2.70,1,False.
1,OH,107,415,371-7191,no,yes,26,161.6,123,27.47,...,103,16.62,254.4,103,11.45,13.7,3,3.70,1,False.
2,NJ,137,415,358-1921,no,no,0,243.4,114,41.38,...,110,10.30,162.6,104,7.32,12.2,5,3.29,0,False.
3,OH,84,408,375-9999,yes,no,0,299.4,71,50.90,...,88,5.26,196.9,89,8.86,6.6,7,1.78,2,False.
4,OK,75,415,330-6626,yes,no,0,166.7,113,28.34,...,122,12.61,186.9,121,8.41,10.1,3,2.73,3,False.

Veamos como podemos saber cuál es el encabezado de este conjunto de datos (los nombres de las columnas).

In [ ]:
print(data2.columns.values)

['State' 'Account Length' 'Area Code' 'Phone' "Int'l Plan" 'VMail Plan'
 'VMail Message' 'Day Mins' 'Day Calls' 'Day Charge' 'Eve Mins'
 'Eve Calls' 'Eve Charge' 'Night Mins' 'Night Calls' 'Night Charge'
 'Intl Mins' 'Intl Calls' 'Intl Charge' 'CustServ Calls' 'Churn?']

También podemos hacerlo de esta manera:

In [ ]:
data2.columns.values

array(['State', 'Account Length', 'Area Code', 'Phone', "Int'l Plan",
       'VMail Plan', 'VMail Message', 'Day Mins', 'Day Calls',
       'Day Charge', 'Eve Mins', 'Eve Calls', 'Eve Charge', 'Night Mins',
       'Night Calls', 'Night Charge', 'Intl Mins', 'Intl Calls',
       'Intl Charge', 'CustServ Calls', 'Churn?'], dtype=object)

In [ ]:
original_data2_cols = data2.columns.values

Si quisieramos cambiar el nombre de las columnas, se procede del modo siguiente (ya tenemos el documento de las columnas en el Drive).

In [ ]:
data2_cols_path = "/content/drive/MyDrive/Machine Learning - Python/Datasets - Machine Learning/customer-churn-model/Customer Churn Columns.csv"
data2_cols = pd.read_csv(data2_cols_path)
data2_cols

   Column_Names
0             A
1             B
2             C
3             D
4             E
5             F
6             G
7             H
8             I
9             J
10            K
11            L
12            M
13            N
14            O
15            P
16            Q
17            R
18            S
19            T
20            U

Veamos la columna (única) de "Column_Names"

In [ ]:
data2_cols["Column_Names"]

0     A
1     B
2     C
3     D
4     E
5     F
6     G
7     H
8     I
9     J
10    K
11    L
12    M
13    N
14    O
15    P
16    Q
17    R
18    S
19    T
20    U
Name: Column_Names, dtype: object

Luego, transformamos la columna `Column_Names` de `data2_cols` a una lista (podríamos usar también el método `tolist()`:

In [ ]:
list_data2_cols = data2_cols["Column_Names"].tolist()
list_data2_cols

['A',
 'B',
 'C',
 'D',
 'E',
 'F',
 'G',
 'H',
 'I',
 'J',
 'K',
 'L',
 'M',
 'N',
 'O',
 'P',
 'Q',
 'R',
 'S',
 'T',
 'U']

In [ ]:
data2_cols_list = list(data2_cols["Column_Names"])
data2_cols_list

['A',
 'B',
 'C',
 'D',
 'E',
 'F',
 'G',
 'H',
 'I',
 'J',
 'K',
 'L',
 'M',
 'N',
 'O',
 'P',
 'Q',
 'R',
 'S',
 'T',
 'U']

Veamos los cambios en data2:

In [ ]:
data2 = pd.read_csv(path2, header = None, names = data2_cols_list)
data2.head()

,A,B,C,D,E,F,G,H,I,J,...,L,M,N,O,P,Q,R,S,T,U
0,State,Account Length,Area Code,Phone,Int'l Plan,VMail Plan,VMail Message,Day Mins,Day Calls,Day Charge,...,Eve Calls,Eve Charge,Night Mins,Night Calls,Night Charge,Intl Mins,Intl Calls,Intl Charge,CustServ Calls,Churn?
1,KS,128,415,382-4657,no,yes,25,265.100000,110,45.070000,...,99,16.780000,244.700000,91,11.010000,10.000000,3,2.700000,1,False.
2,OH,107,415,371-7191,no,yes,26,161.600000,123,27.470000,...,103,16.620000,254.400000,103,11.450000,13.700000,3,3.700000,1,False.
3,NJ,137,415,358-1921,no,no,0,243.400000,114,41.380000,...,110,10.300000,162.600000,104,7.320000,12.200000,5,3.290000,0,False.
4,OH,84,408,375-9999,yes,no,0,299.400000,71,50.900000,...,88,5.260000,196.900000,89,8.860000,6.600000,7,1.780000,2,False.

In [ ]:
# Verifiquemos cuales son las columnas de data2

print(data2.columns.values)

['A' 'B' 'C' 'D' 'E' 'F' 'G' 'H' 'I' 'J' 'K' 'L' 'M' 'N' 'O' 'P' 'Q' 'R'
 'S' 'T' 'U']

#Usando el método `open()`

In [ ]:
data3 = open(path2)

In [ ]:
data3.readline()

"State,Account Length,Area Code,Phone,Int'l Plan,VMail Plan,VMail Message,Day Mins,Day Calls,Day Charge,Eve Mins,Eve Calls,Eve Charge,Night Mins,Night Calls,Night Charge,Intl Mins,Intl Calls,Intl Charge,CustServ Calls,Churn?\n"

In [ ]:
data3.seek(0) # Esto es para leer la primera linea nuevamente

0

In [ ]:
data3.readline().strip()

"State,Account Length,Area Code,Phone,Int'l Plan,VMail Plan,VMail Message,Day Mins,Day Calls,Day Charge,Eve Mins,Eve Calls,Eve Charge,Night Mins,Night Calls,Night Charge,Intl Mins,Intl Calls,Intl Charge,CustServ Calls,Churn?"

In [ ]:
data3.seek(0)

0

In [ ]:
data3.readline().strip().split(",")

['State',
 'Account Length',
 'Area Code',
 'Phone',
 "Int'l Plan",
 'VMail Plan',
 'VMail Message',
 'Day Mins',
 'Day Calls',
 'Day Charge',
 'Eve Mins',
 'Eve Calls',
 'Eve Charge',
 'Night Mins',
 'Night Calls',
 'Night Charge',
 'Intl Mins',
 'Intl Calls',
 'Intl Charge',
 'CustServ Calls',
 'Churn?']

In [ ]:
data3.seek(0)

0

In [ ]:
cols = data3.readline().strip().split(",")
cols

['State',
 'Account Length',
 'Area Code',
 'Phone',
 "Int'l Plan",
 'VMail Plan',
 'VMail Message',
 'Day Mins',
 'Day Calls',
 'Day Charge',
 'Eve Mins',
 'Eve Calls',
 'Eve Charge',
 'Night Mins',
 'Night Calls',
 'Night Charge',
 'Intl Mins',
 'Intl Calls',
 'Intl Charge',
 'CustServ Calls',
 'Churn?']

In [ ]:
n_cols = len(cols)
n_cols

21

Si quisiera conocer el número de filas de data3 (o de data2):

In [ ]:
main_dict = {}
for col in cols:
  main_dict[col] = []

In [ ]:
main_dict

{'State': [],
 'Account Length': [],
 'Area Code': [],
 'Phone': [],
 "Int'l Plan": [],
 'VMail Plan': [],
 'VMail Message': [],
 'Day Mins': [],
 'Day Calls': [],
 'Day Charge': [],
 'Eve Mins': [],
 'Eve Calls': [],
 'Eve Charge': [],
 'Night Mins': [],
 'Night Calls': [],
 'Night Charge': [],
 'Intl Mins': [],
 'Intl Calls': [],
 'Intl Charge': [],
 'CustServ Calls': [],
 'Churn?': []}

In [ ]:
for col in original_data2_cols:
    print(col)

State
Account Length
Area Code
Phone
Int'l Plan
VMail Plan
VMail Message
Day Mins
Day Calls
Day Charge
Eve Mins
Eve Calls
Eve Charge
Night Mins
Night Calls
Night Charge
Intl Mins
Intl Calls
Intl Charge
CustServ Calls
Churn?

In [ ]:
cols[3]

'Phone'

In [ ]:
counted = 0
for line in data3:
  values = line.strip().split(",")
  for i in range(len(cols)):
    main_dict[cols[i]].append(values[i])
  counted += 1
print("El dataset tiene {} filas y {} columnas".format(counted, len(original_data2_cols)))

El dataset tiene 3333 filas y 21 columnas

In [ ]:
data3 = open(path2)

In [ ]:
# Aquí he cargado nuevamente el método open al path2, y aplicado una vez el método readline().strip().split(",")
counter = 0
for line in data3:
    counter += 1

print(counter)

3334

In [ ]:
print(main_dict)

{'State': ['KS', 'OH', 'NJ', 'OH', 'OK', 'AL', 'MA', 'MO', 'LA', 'WV', 'IN', 'RI', 'IA', 'MT', 'IA', 'NY', 'ID', 'VT', 'VA', 'TX', 'FL', 'CO', 'AZ', 'SC', 'VA', 'NE', 'WY', 'MT', 'MO', 'HI', 'IL', 'NH', 'LA', 'AZ', 'OK', 'GA', 'AK', 'MA', 'AK', 'NJ', 'GA', 'MD', 'AR', 'ID', 'WI', 'OR', 'MI', 'DE', 'ID', 'WY', 'IA', 'IN', 'VA', 'UT', 'WY', 'IN', 'CO', 'CO', 'WI', 'OK', 'ID', 'CA', 'MN', 'SD', 'NC', 'WA', 'WY', 'MN', 'UT', 'TX', 'NJ', 'MN', 'NM', 'NV', 'HI', 'MN', 'DC', 'NY', 'MN', 'MD', 'WV', 'OR', 'CO', 'GA', 'TX', 'VT', 'IN', 'WV', 'KY', 'NJ', 'DC', 'LA', 'AR', 'ME', 'AZ', 'AK', 'MT', 'AZ', 'MS', 'ID', 'IA', 'MA', 'VT', 'KY', 'IN', 'AZ', 'MI', 'NM', 'CO', 'UT', 'MI', 'MA', 'AL', 'DE', 'AZ', 'ME', 'NJ', 'NV', 'MO', 'ID', 'NE', 'TX', 'MD', 'MS', 'NV', 'AZ', 'MS', 'MS', 'TX', 'NE', 'NE', 'CA', 'NJ', 'TX', 'AR', 'AL', 'NY', 'FL', 'AK', 'NV', 'DE', 'MD', 'MI', 'VT', 'VT', 'MI', 'WA', 'UT', 'LA', 'RI', 'IA', 'NE', 'OH', 'RI', 'OK', 'LA', 'OH', 'VA', 'MO', 'FL', 'SC', 'VA', 'IA', 'MI', 'OK', 'DE', 'GA', 'DC', 'AZ', 'AL', 'CO', 'NH', 'NM', 'OR', 'LA', 'NE', 'MN', 'MI', 'AR', 'KS', 'WV', 'AK', 'NY', 'NH', 'VA', 'NM', 'NY', 'AZ', 'WY', 'WA', 'CO', 'TX', 'KY', 'MT', 'OK', 'MD', 'TN', 'TX', 'ME', 'DC', 'MN', 'DE', 'MD', 'MI', 'WA', 'MO', 'IN', 'OR', 'MD', 'RI', 'LA', 'AZ', 'PA', 'AZ', 'FL', 'LA', 'FL', 'FL', 'MD', 'AL', 'WA', 'TN', 'MS', 'ME', 'OK', 'IN', 'MO', 'IA', 'VA', 'KY', 'MD', 'OH', 'OK', 'NV', 'ID', 'MN', 'SD', 'IL', 'WY', 'AL', 'NJ', 'NV', 'IN', 'WV', 'VA', 'SC', 'RI', 'IN', 'AZ', 'NM', 'OR', 'NJ', 'MS', 'MI', 'TX', 'FL', 'DC', 'TX', 'KS', 'UT', 'MN', 'IL', 'NM', 'SC', 'NC', 'WV', 'RI', 'NH', 'MO', 'MA', 'PA', 'OK', 'AL', 'WY', 'PA', 'WA', 'HI', 'SD', 'AL', 'VT', 'MT', 'MN', 'AK', 'MI', 'DE', 'SD', 'MI', 'KS', 'AL', 'OK', 'CT', 'NE', 'WI', 'CT', 'WI', 'IN', 'DC', 'AR', 'ME', 'MN', 'MD', 'FL', 'RI', 'IA', 'AZ', 'MO', 'VT', 'IN', 'RI', 'SD', 'MN', 'TX', 'VA', 'MA', 'ID', 'MA', 'GA', 'RI', 'ID', 'SD', 'MA', 'WY', 'VA', 'OR', 'VA', 'ME', 'AL', 'GA', 'IA', 'AZ', 'FL', 'MT', 'AL', 'DE', 'MT', 'KY', 'SC', 'WA', 'OR', 'AK', 'GA', 'MN', 'IL', 'IN', 'SC', 'VA', 'WI', 'VT', 'AZ', 'FL', 'AK', 'AR', 'AR', 'AK', 'MS', 'ME', 'CA', 'NM', 'NE', 'SC', 'CO', 'DE', 'OH', 'MS', 'OK', 'CO', 'NC', 'MD', 'KS', 'MA', 'NC', 'NM', 'CA', 'NY', 'AZ', 'SD', 'DC', 'ND', 'MO', 'KS', 'SD', 'OK', 'OR', 'IN', 'OH', 'KS', 'CT', 'NH', 'WI', 'MS', 'WV', 'MA', 'MD', 'PA', 'WI', 'TN', 'TX', 'OR', 'IL', 'DC', 'GA', 'ID', 'UT', 'KY', 'OH', 'WI', 'IL', 'DE', 'RI', 'TX', 'OR', 'NV', 'NE', 'MS', 'OR', 'DE', 'DE', 'AZ', 'SD', 'NV', 'NM', 'MN', 'NJ', 'IN', 'DC', 'MA', 'ME', 'NH', 'AZ', 'OR', 'KS', 'NE', 'MI', 'SC', 'PA', 'MT', 'NM', 'OH', 'WY', 'MI', 'AR', 'FL', 'AR', 'MO', 'WI', 'TX', 'TX', 'NM', 'GA', 'ID', 'AL', 'KS', 'SD', 'LA', 'OH', 'MA', 'AZ', 'KY', 'DC', 'WA', 'UT', 'RI', 'OH', 'NV', 'ND', 'NV', 'FL', 'MD', 'AZ', 'AL', 'NE', 'NV', 'IL', 'WV', 'MI', 'AR', 'UT', 'GA', 'AZ', 'ID', 'HI', 'NV', 'MD', 'GA', 'GA', 'UT', 'MA', 'IN', 'VT', 'IA', 'IN', 'AL', 'ME', 'RI', 'MD', 'FL', 'CA', 'AL', 'ME', 'WV', 'SD', 'FL', 'MI', 'MI', 'NM', 'AK', 'OH', 'MO', 'KS', 'MS', 'VT', 'NE', 'VA', 'DE', 'AL', 'ID', 'MS', 'OK', 'NM', 'WI', 'WV', 'SC', 'KY', 'MO', 'IL', 'OK', 'MI', 'NJ', 'ID', 'DC', 'NY', 'AL', 'OR', 'OK', 'LA', 'NE', 'TX', 'UT', 'OR', 'NY', 'AL', 'RI', 'MN', 'NC', 'MD', 'RI', 'WI', 'VT', 'CT', 'OK', 'AK', 'NY', 'GA', 'UT', 'NM', 'NE', 'NJ', 'TX', 'MT', 'CO', 'VT', 'RI', 'WY', 'ID', 'CT', 'ME', 'AZ', 'MD', 'IN', 'NC', 'DE', 'MN', 'WI', 'FL', 'WV', 'SD', 'FL', 'OR', 'CO', 'CT', 'IN', 'PA', 'NM', 'ME', 'SD', 'AR', 'TX', 'NH', 'OK', 'WI', 'AL', 'PA', 'OK', 'ME', 'WV', 'HI', 'MN', 'NY', 'AZ', 'OH', 'MI', 'MA', 'WV', 'MI', 'NM', 'MO', 'RI', 'NC', 'WY', 'WY', 'PA', 'KY', 'OR', 'NV', 'DC', 'UT', 'WA', 'FL', 'VA', 'KS', 'KS', 'DC', 'ME', 'LA', 'DC', 'TX', 'NJ', 'DE', 'VT', 'GA', 'TX', 'MT', 'ND', 'NJ', 'MO', 'CO', 'KS', 'NC', 'MT', 'DE', 'ND', 'VA', 'IL', 'OK', 'CO', 'MT', 'WV', 'ME', 'WI', 'MO', 'NY', 'CT', 'AR', 'WY', 'CA', 'CA', 'MN', 'AK', 'VA', 'CO', 'MT', 'SD', 'NE', 'VT', 'ND', 'GA', 'OR', 'MT', 'WY', 'GA', 'WV', 'CT', 'IL', 'CO', 'DE', 'LA', 'MA', 'IN', 'NY', 'TX', 'KS', 'WV', 'NE', 'ND', 'AK', 'CO', 'ME', 'SC', 'MN', 'CO', 'KS', 'MS', 'NE', 'NJ', 'WI', 'MT', 'AR', 'WA', 'NH', 'IA', 'WV', 'RI', 'KS', 'MT', 'MO', 'HI', 'CO', 'CT', 'ID', 'DC', 'TN', 'WY', 'MO', 'VA', 'SD', 'WV', 'GA', 'AZ', 'AK', 'AK', 'CT', 'UT', 'KY', 'MI', 'OR', 'TN', 'WV', 'NJ', 'MS', 'ME', 'WY', 'WY', 'IN', 'NM', 'NJ', 'DC', 'UT', 'KY', 'KS', 'MI', 'UT', 'NE', 'FL', 'LA', 'MT', 'WA', 'MI', 'KY', 'LA', 'NM', 'AL', 'MO', 'CO', 'TX', 'NY', 'OR', 'WY', 'UT', 'LA', 'NV', 'NC', 'NC', 'WY', 'TN', 'FL', 'CA', 'PA', 'WV', 'NJ', 'MT', 'MN', 'WI', 'ID', 'MA', 'OR', 'MT', 'AL', 'ND', 'LA', 'ND', 'MS', 'WV', 'WI', 'KS', 'MO', 'PA', 'SD', 'NJ', 'AL', 'ME', 'AZ', 'VT', 'NV', 'WI', 'HI', 'DE', 'AZ', 'VA', 'GA', 'AZ', 'MN', 'ME', 'FL', 'WA', 'MT', 'AL', 'WV', 'GA', 'OH', 'DE', 'NE', 'FL', 'AK', 'WI', 'WA', 'KY', 'OH', 'UT', 'NM', 'MN', 'WV', 'MN', 'AL', 'PA', 'DE', 'MO', 'IL', 'FL', 'HI', 'ME', 'CO', 'NH', 'SC', 'IN', 'FL', 'GA', 'IL', 'NC', 'VT', 'DC', 'VT', 'NV', 'OR', 'AL', 'ND', 'FL', 'NE', 'ND', 'ME', 'IL', 'WA', 'MA', 'KS', 'RI', 'MO', 'IA', 'WY', 'NV', 'WI', 'AL', 'HI', 'MO', 'CA', 'MO', 'CT', 'MD', 'OH', 'NV', 'MD', 'NE', 'OH', 'MA', 'OK', 'MA', 'WA', 'HI', 'CO', 'FL', 'WI', 'ID', 'WY', 'GA', 'FL', 'WY', 'DE', 'ME', 'DC', 'IA', 'CO', 'MN', 'VT', 'AZ', 'LA', 'MO', 'ME', 'MD', 'VT', 'DC', 'WY', 'VA', 'VA', 'CT', 'HI', 'WI', 'MD', 'WV', 'VT', 'UT', 'CO', 'NC', 'NJ', 'AR', 'IA', 'GA', 'MO', 'MO', 'WY', 'HI', 'PA', 'TX', 'VA', 'RI', 'WI', 'MS', 'KY', 'NC', 'NV', 'UT', 'ME', 'HI', 'OH', 'WV', 'OK', 'KY', 'AL', 'MD', 'NE', 'DC', 'TX', 'OH', 'DE', 'IA', 'VT', 'OR', 'NV', 'NC', 'NJ', 'MN', 'ID', 'AL', 'AK', 'VT', 'PA', 'AK', 'CA', 'MS', 'AR', 'NV', 'AL', 'GA', 'AR', 'MA', 'NJ', 'MO', 'NY', 'AZ', 'NJ', 'WV', 'NM', 'SC', 'VT', 'TN', 'LA', 'OH', 'OR', 'DE', 'KY', 'GA', 'VT', 'OR', 'TX', 'MO', 'ND', 'MN', 'NV', 'NY', 'FL', 'KS', 'NV', 'NV', 'SC', 'MI', 'MI', 'TN', 'NY', 'NV', 'IL', 'MS', 'ND', 'NC', 'MI', 'TN', 'VT', 'OK', 'DE', 'ND', 'OR', 'NY', 'MO', 'FL', 'ND', 'NY', 'ND', 'NY', 'OH', 'AL', 'SC', 'GA', 'WY', 'WV', 'HI', 'WV', 'LA', 'AR', 'AK', 'DC', 'AL', 'UT', 'KS', 'MN', 'VA', 'UT', 'IN', 'CT', 'DE', 'VT', 'MO', 'RI', 'CA', 'RI', 'CT', 'IN', 'FL', 'KS', 'NY', 'TX', 'RI', 'NV', 'UT', 'OK', 'MN', 'NC', 'OR', 'NH', 'AK', 'OR', 'KS', 'WV', 'GA', 'NM', 'OH', 'ND', 'RI', 'HI', 'WY', 'NY', 'KS', 'LA', 'PA', 'NV', 'MN', 'PA', 'MO', 'NY', 'ME', 'NH', 'WY', 'NY', 'ME', 'MN', 'OH', 'NC', 'SD', 'UT', 'KY', 'MT', 'NJ', 'FL', 'IN', 'DE', 'AL', 'ME', 'SD', 'VA', 'AK', 'ID', 'RI', 'KY', 'ND', 'HI', 'WI', 'WV', 'NJ', 'KS', 'AL', 'NJ', 'NC', 'DE', 'WY', 'ID', 'NY', 'MO', 'ID', 'IA', 'TN', 'OH', 'IL', 'FL', 'MA', 'OK', 'KY', 'MI', 'NE', 'VA', 'NY', 'MT', 'VT', 'KS', 'VA', 'AL', 'PA', 'AL', 'WV', 'NV', 'TN', 'ID', 'WY', 'TX', 'MA', 'IL', 'LA', 'CO', 'UT', 'MI', 'NH', 'ID', 'WA', 'MN', 'NY', 'MD', 'GA', 'HI', 'AL', 'CT', 'CO', 'KS', 'NJ', 'FL', 'CA', 'KS', 'TX', 'MN', 'AK', 'OR', 'MS', 'VT', 'UT', 'KS', 'NV', 'DE', 'IN', 'TX', 'MA', 'VT', 'CA', 'IA', 'NH', 'GA', 'WI', 'CO', 'SC', 'MI', 'MD', 'IN', 'ME', 'DC', 'TN', 'FL', 'WA', 'HI', 'NE', 'TN', 'MD', 'NM', 'VT', 'OR', 'IN', 'MO', 'FL', 'DC', 'VT', 'OH', 'MO', 'LA', 'IL', 'NJ', 'IA', 'WA', 'NE', 'CT', 'WV', 'ND', 'UT', 'MS', 'MN', 'NH', 'LA', 'ME', 'KS', 'KS', 'NV', 'MT', 'MT', 'ID', 'AK', 'UT', 'AR', 'LA', 'KS', 'OR', 'WI', 'CO', 'KS', 'IL', 'IA', 'AZ', 'NE', 'ID', 'OH', 'TX', 'TN', 'OK', 'ND', 'MT', 'NC', 'MN', 'MN', 'MA', 'PA', 'GA', 'NV', 'TX', 'ME', 'RI', 'MN', 'NH', 'TN', 'UT', 'RI', 'NH', 'AK', 'NC', 'AZ', 'MA', 'TN', 'WY', 'IA', 'IN', 'NJ', 'FL', 'MT', 'ND', 'MI', 'MT', 'AL', 'NV', 'MI', 'FL', 'NY', 'KS', 'NC', 'MN', 'RI', 'UT', 'OR', 'SC', 'IL', 'OH', 'MA', 'OR', 'CA', 'WV', 'VT', 'ID', 'OR', 'GA', 'ME', 'HI', 'AZ', 'UT', 'IA', 'CT', 'WA', 'VA', 'CO', 'LA', 'TX', 'SD', 'VA', 'NY', 'WA', 'WI', 'TN', 'CT', 'WA', 'NH', 'MT', 'NE', 'WA', 'WI', 'AR', 'WI', 'DE', 'NH', 'VA', 'TN', 'VA', 'ID', 'TN', 'AZ', 'MT', 'OK', 'ID', 'NV', 'KS', 'WY', 'MS', 'WY', 'TX', 'WA', 'HI', 'IL', 'AK', 'MD', 'MA', 'SD', 'PA', 'NC', 'VT', 'KY', 'WA', 'LA', 'WA', 'ME', 'WI', 'TX', 'IA', 'AZ', 'ND', 'VT', 'HI', 'WY', 'WV', 'OK', 'CT', 'UT', 'NY', 'VA', 'VT', 'SD', 'PA', 'ND', 'CT', 'SC', 'MI', 'VT', 'OH', 'VT', 'IL', 'MO', 'WI', 'NJ', 'GA', 'VT', 'CT', 'AZ', 'SD', 'CT', 'IN', 'OH', 'NY', 'NE', 'OK', 'NC', 'HI', 'UT', 'MD', 'VT', 'TX', 'AZ', 'VA', 'WI', 'NE', 'KY', 'NV', 'MT', 'MO', 'MS', 'NM', 'NJ', 'NH', 'NC', 'MT', 'SD', 'VA', 'LA', 'NV', 'AK', 'OH', 'NM', 'MI', 'MN', 'WY', 'WY', 'WA', 'NM', 'VA', 'RI', 'AL', 'WV', 'WV', 'NJ', 'TN', 'MI', 'UT', 'IL', 'MI', 'WI', 'ND', 'VT', 'WA', 'NC', 'ME', 'SD', 'WV', 'ID', 'LA', 'GA', 'FL', 'CO', 'NV', 'IN', 'VA', 'UT', 'UT', 'MO', 'CT', 'HI', 'MD', 'VA', 'MT', 'SC', 'CO', 'ID', 'AL', 'CO', 'UT', 'DE', 'OH', 'RI', 'FL', 'OH', 'MD', 'IL', 'PA', 'AZ', 'NH', 'RI', 'HI', 'NJ', 'WI', 'MD', 'OR', 'NV', 'AR', 'MT', 'CT', 'UT', 'GA', 'NV', 'TN', 'DE', 'NY', 'MT', 'IA', 'VT', 'LA', 'MT', 'NH', 'WV', 'ID', 'AZ', 'SC', 'WV', 'OH', 'MD', 'MD', 'MN', 'NE', 'MN', 'NY', 'HI', 'MO', 'NV', 'MA', 'NH', 'UT', 'FL', 'WA', 'CT', 'KY', 'NM', 'ND', 'NV', 'CA', 'ID', 'OK', 'IA', 'OH', 'NJ', 'IA', 'DE', 'CA', 'WY', 'OR', 'ME', 'AR', 'ME', 'WV', 'PA', 'HI', 'MT', 'DC', 'AR', 'MS', 'OH', 'MO', 'TX', 'MD', 'CT', 'SC', 'MI', 'SD', 'CO', 'ID', 'AZ', 'FL', 'MN', 'DE', 'MI', 'MS', 'MA', 'CA', 'MN', 'VT', 'CT', 'WV', 'WV', 'NE', 'NC', 'NE', 'IL', 'MA', 'AZ', 'SD', 'MT', 'VT', 'UT', 'HI', 'DC', 'WI', 'UT', 'WA', 'SD', 'MT', 'NJ', 'CT', 'VA', 'NC', 'AK', 'MD', 'IL', 'CT', 'KS', 'MA', 'NJ', 'AR', 'MS', 'ND', 'IN', 'MI', 'AR', 'VT', 'WV', 'ME', 'IA', 'CT', 'NM', 'OR', 'VT', 'RI', 'RI', 'NM', 'AL', 'MT', 'CT', 'TN', 'ID', 'TX', 'NH', 'ND', 'SC', 'KS', 'ME', 'RI', 'WI', 'NC', 'OH', 'WY', 'NJ', 'ND', 'WI', 'KY', 'NY', 'MO', 'AZ', 'MN', 'CO', 'MD', 'AR', 'TN', 'DE', 'TN', 'WI', 'WV', 'CT', 'MN', 'MO', 'VA', 'NH', 'OK', 'CT', 'TN', 'MD', 'WI', 'SD', 'ND', 'VA', 'UT', 'MA', 'SD', 'AL', 'AL', 'WV', 'SC', 'FL', 'KY', 'UT', 'NY', 'MS', 'NH', 'VA', 'VT', 'WY', 'NV', 'WV', 'WA', 'KS', 'VT', 'OK', 'GA', 'CO', 'AK', 'TN', 'KY', 'PA', 'CT', 'CT', 'MN', 'WY', 'PA', 'OR', 'PA', 'OK', 'VT', 'ID', 'PA', 'NM', 'FL', 'TX', 'VT', 'MA', 'OR', 'DE', 'FL', 'ID', 'MD', 'WV', 'ID', 'NV', 'OH', 'ID', 'SC', 'MO', 'NE', 'NC', 'ME', 'MI', 'AZ', 'AZ', 'HI', 'NJ', 'MS', 'MA', 'SC', 'MN', 'WV', 'MS', 'VA', 'MS', 'NM', 'TX', 'HI', 'WA', 'WI', 'CO', 'NV', 'RI', 'VA', 'NJ', 'ND', 'MN', 'HI', 'ND', 'WI', 'MN', 'DC', 'KS', 'MT', 'WV', 'ME', 'WY', 'NY', 'VT', 'NC', 'MO', 'NC', 'NJ', 'OH', 'TX', 'WA', 'TN', 'HI', 'WY', 'CT', 'NM', 'NJ', 'AL', 'MN', 'NC', 'OH', 'ND', 'CO', 'ND', 'NY', 'WI', 'WY', 'OR', 'CO', 'LA', 'AL', 'TX', 'PA', 'IL', 'DE', 'MO', 'AR', 'OH', 'WI', 'GA', 'KY', 'OH', 'TN', 'SD', 'NY', 'GA', 'TX', 'WV', 'MI', 'ND', 'NE', 'SD', 'NJ', 'AK', 'CT', 'CO', 'MD', 'ND', 'NH', 'MN', 'KY', 'NH', 'CO', 'KY', 'KY', 'IN', 'OR', 'SD', 'DE', 'OR', 'NE', 'OH', 'OH', 'AR', 'KS', 'TX', 'WI', 'OR', 'VA', 'AR', 'CT', 'OH', 'WY', 'IL', 'MO', 'DC', 'MA', 'NH', 'IA', 'AL', 'OR', 'WV', 'WA', 'NV', 'SC', 'NC', 'NH', 'WY', 'FL', 'PA', 'NC', 'MO', 'KS', 'KY', 'DE', 'WI', 'CO', 'NM', 'DE', 'IL', 'WA', 'MA', 'OH', 'TN', 'MA', 'MI', 'TX', 'NH', 'MD', 'MS', 'AZ', 'IN', 'NY', 'WI', 'WV', 'NY', 'OK', 'NC', 'KY', 'TX', 'CT', 'NE', 'HI', 'SC', 'AK', 'SD', 'ID', 'OK', 'WA', 'SD', 'OH', 'VA', 'WI', 'IN', 'NM', 'HI', 'KY', 'OH', 'VT', 'AZ', 'VT', 'MO', 'AL', 'NJ', 'WA', 'NY', 'DC', 'NE', 'MA', 'VT', 'NM', 'CO', 'NH', 'IL', 'UT', 'WV', 'NJ', 'NM', 'ND', 'WA', 'NM', 'DE', 'GA', 'HI', 'CT', 'NJ', 'ME', 'OK', 'TN', 'WY', 'NY', 'DE', 'RI', 'PA', 'HI', 'MD', 'VA', 'IN', 'OR', 'AZ', 'WI', 'VA', 'MO', 'NV', 'HI', 'WA', 'IL', 'IL', 'LA', 'WI', 'TX', 'MI', 'NC', 'WA', 'ND', 'NE', 'MS', 'KY', 'RI', 'NY', 'TX', 'DE', 'NM', 'RI', 'MS', 'NY', 'NE', 'WI', 'KY', 'SD', 'VA', 'KS', 'ND', 'CO', 'KY', 'WA', 'NV', 'SC', 'RI', 'ID', 'KY', 'ME', 'SD', 'SC', 'TN', 'MT', 'WI', 'AK', 'AZ', 'MT', 'DE', 'VA', 'MA', 'IN', 'MD', 'NV', 'CO', 'KS', 'AR', 'WY', 'PA', 'TX', 'NY', 'OR', 'CA', 'NY', 'AR', 'MI', 'OK', 'TX', 'NC', 'ID', 'IL', 'OR', 'SD', 'NE', 'RI', 'MD', 'ID', 'ME', 'SD', 'NY', 'DE', 'OK', 'SC', 'IN', 'NV', 'IL', 'SD', 'OK', 'KS', 'IA', 'NJ', 'NJ', 'MT', 'IA', 'WA', 'NE', 'TX', 'MS', 'IA', 'WI', 'MT', 'GA', 'MT', 'ND', 'VT', 'SD', 'OH', 'OH', 'MT', 'IL', 'NV', 'UT', 'NH', 'LA', 'VT', 'NY', 'CT', 'KS', 'MI', 'SD', 'ME', 'MD', 'VA', 'NJ', 'TN', 'DC', 'DC', 'OR', 'RI', 'AK', 'WI', 'IN', 'MI', 'ID', 'NH', 'MN', 'AZ', 'MN', 'MO', 'AL', 'PA', 'AK', 'MS', 'IA', 'WY', 'NE', 'ND', 'CT', 'NC', 'CT', 'ND', 'WA', 'NV', 'CO', 'KS', 'CO', 'MO', 'MA', 'NY', 'AK', 'WI', 'NH', 'TN', 'NY', 'GA', 'MN', 'MI', 'ID', 'CT', 'NC', 'LA', 'NJ', 'TX', 'CA', 'MD', 'WY', 'TX', 'CA', 'UT', 'WA', 'MS', 'OH', 'KS', 'RI', 'IN', 'VT', 'MT', 'CT', 'NM', 'OH', 'GA', 'MN', 'CT', 'AL', 'WV', 'NH', 'WY', 'VA', 'VT', 'OH', 'MT', 'MA', 'VA', 'NM', 'AR', 'NE', 'WY', 'IA', 'SC', 'NC', 'HI', 'UT', 'WY', 'AL', 'VA', 'WI', 'FL', 'KS', 'NV', 'NY', 'VA', 'KS', 'NC', 'MO', 'ND', 'CA', 'WV', 'IL', 'NY', 'NV', 'AL', 'KS', 'ND', 'OK', 'UT', 'OH', 'WY', 'NM', 'AL', 'DC', 'ID', 'AR', 'ID', 'TX', 'NM', 'WA', 'UT', 'RI', 'NC', 'RI', 'NY', 'TX', 'DE', 'MS', 'OH', 'LA', 'FL', 'WA', 'WV', 'NY', 'NE', 'PA', 'MS', 'IN', 'VA', 'MN', 'DE', 'OR', 'UT', 'CT', 'AL', 'TX', 'CT', 'MS', 'AR', 'CA', 'MI', 'WV', 'DE', 'FL', 'AK', 'ID', 'OH', 'NH', 'MA', 'SC', 'OR', 'OH', 'NC', 'KY', 'ID', 'WA', 'WV', 'RI', 'KS', 'NV', 'NE', 'FL', 'WY', 'WA', 'CO', 'WI', 'KS', 'RI', 'MT', 'CO', 'CT', 'FL', 'VT', 'OH', 'NH', 'RI', 'FL', 'MD', 'WY', 'FL', 'TN', 'NC', 'IN', 'IA', 'WV', 'UT', 'GA', 'AK', 'UT', 'MS', 'AR', 'AK', 'AK', 'ME', 'WV', 'CT', 'GA', 'NV', 'VT', 'DC', 'TN', 'OR', 'MS', 'NC', 'CO', 'AR', 'PA', 'MN', 'NM', 'UT', 'NE', 'MS', 'NV', 'OR', 'VA', 'NJ', 'WV', 'OR', 'KY', 'MO', 'TX', 'MN', 'FL', 'PA', 'WV', 'IN', 'OK', 'NE', 'DE', 'MI', 'IL', 'UT', 'IL', 'WA', 'NM', 'MD', 'VA', 'MT', 'CT', 'AL', 'WV', 'MO', 'ND', 'AR', 'GA', 'FL', 'LA', 'UT', 'AZ', 'NY', 'KY', 'AL', 'IN', 'IN', 'FL', 'NM', 'AL', 'MN', 'NY', 'MD', 'KS', 'WV', 'ID', 'LA', 'MI', 'TN', 'CA', 'FL', 'LA', 'IL', 'AL', 'CT', 'PA', 'TX', 'VA', 'MO', 'MT', 'ND', 'FL', 'WI', 'KY', 'MD', 'IN', 'MA', 'ND', 'VT', 'CT', 'VA', 'MS', 'AK', 'WY', 'NY', 'NC', 'IL', 'OH', 'RI', 'WY', 'OR', 'NV', 'ND', 'OR', 'ND', 'NJ', 'WV', 'VA', 'ID', 'CT', 'NM', 'CT', 'MI', 'SC', 'SC', 'NY', 'MT', 'WY', 'NE', 'IN', 'CO', 'WY', 'MD', 'OK', 'SD', 'SC', 'NY', 'NY', 'WV', 'WA', 'ID', 'MN', 'TX', 'AZ', 'DE', 'CO', 'WI', 'WI', 'NJ', 'IL', 'DC', 'IA', 'GA', 'AK', 'CA', 'MN', 'CO', 'KY', 'SC', 'MT', 'KY', 'WV', 'ID', 'MN', 'MA', 'MD', 'SD', 'PA', 'KY', 'ID', 'NY', 'NM', 'CA', 'ID', 'WY', 'NM', 'HI', 'ID', 'NC', 'TX', 'GA', 'AL', 'ME', 'VA', 'ID', 'NY', 'NC', 'OH', 'HI', 'DC', 'TN', 'VT', 'MD', 'LA', 'HI', 'FL', 'WY', 'NE', 'WY', 'OR', 'IN', 'MD', 'TN', 'WV', 'WA', 'MS', 'OH', 'IN', 'CO', 'TX', 'AK', 'WV', 'MA', 'TN', 'ID', 'DE', 'VA', 'MT', 'ID', 'IN', 'MD', 'MS', 'WA', 'OH', 'RI', 'AR', 'AZ', 'SC', 'KY', 'AL', 'NE', 'MT', 'MN', 'NV', 'CA', 'UT', 'IL', 'DC', 'IN', 'NM', 'MS', 'VT', 'VT', 'UT', 'KY', 'VA', 'OH', 'AZ', 'NY', 'VA', 'MD', 'MA', 'IL', 'LA', 'MO', 'DC', 'PA', 'TN', 'NJ', 'VA', 'TN', 'NJ', 'WA', 'AR', 'WI', 'WA', 'RI', 'ME', 'CO', 'CO', 'RI', 'CT', 'NC', 'WY', 'OR', 'FL', 'KY', 'SC', 'WA', 'MT', 'PA', 'MA', 'VT', 'MN', 'IL', 'AR', 'MD', 'MT', 'VT', 'CO', 'NC', 'WA', 'TN', 'AR', 'DC', 'MN', 'IA', 'KS', 'ND', 'MT', 'IL', 'DC', 'KY', 'MS', 'TN', 'IA', 'AK', 'MN', 'WV', 'OR', 'MS', 'ME', 'MN', 'GA', 'DC', 'GA', 'NY', 'OK', 'OK', 'GA', 'NJ', 'MN', 'ME', 'MI', 'MT', 'NE', 'ND', 'VA', 'VT', 'OH', 'AL', 'DC', 'ND', 'TN', 'DE', 'NY', 'AL', 'OK', 'MS', 'MD', 'NE', 'AR', 'IL', 'IN', 'UT', 'LA', 'ID', 'KY', 'MI', 'NH', 'WV', 'OR', 'SD', 'MD', 'ND', 'TN', 'MO', 'IL', 'UT', 'MI', 'AR', 'TX', 'AK', 'TN', 'NH', 'NM', 'MN', 'IA', 'RI', 'AL', 'NC', 'SD', 'MT', 'HI', 'MT', 'KY', 'DC', 'CO', 'MI', 'AL', 'KS', 'NC', 'SC', 'CO', 'MN', 'WY', 'FL', 'NY', 'OK', 'ME', 'NE', 'OH', 'CT', 'DC', 'OK', 'NJ', 'IA', 'VA', 'VA', 'NM', 'FL', 'RI', 'NJ', 'NE', 'WV', 'WY', 'SC', 'MS', 'ND', 'IL', 'OR', 'UT', 'IA', 'ME', 'WY', 'WI', 'SC', 'DC', 'CT', 'OR', 'OR', 'NV', 'MN', 'OK', 'KS', 'RI', 'DC', 'IL', 'UT', 'MN', 'WI', 'MI', 'MI', 'MA', 'AL', 'SC', 'WI', 'VT', 'CT', 'OR', 'HI', 'WV', 'RI', 'MI', 'ME', 'WV', 'NE', 'DC', 'NH', 'MD', 'NH', 'WV', 'IL', 'OK', 'NH', 'MI', 'ND', 'LA', 'HI', 'NJ', 'WV', 'NC', 'PA', 'MI', 'WY', 'NJ', 'NJ', 'NC', 'NM', 'MS', 'TX', 'OK', 'ID', 'AL', 'WY', 'HI', 'VA', 'WV', 'DE', 'CA', 'PA', 'CO', 'MD', 'AL', 'AL', 'KS', 'MI', 'AK', 'OH', 'IN', 'SC', 'KS', 'OK', 'WI', 'IN', 'IL', 'TN', 'DC', 'NC', 'RI', 'MS', 'VA', 'KY', 'NV', 'WI', 'NH', 'NE', 'WI', 'NJ', 'ME', 'WY', 'IN', 'WI', 'VT', 'CA', 'IN', 'SC', 'IN', 'IA', 'MD', 'MN', 'AR', 'MS', 'MN', 'WA', 'MS', 'ID', 'NC', 'VA', 'MT', 'MI', 'HI', 'NC', 'MN', 'WV', 'SD', 'HI', 'MS', 'NY', 'LA', 'KS', 'MA', 'AK', 'SD', 'CO', 'NH', 'WV', 'AZ', 'ME', 'NH', 'RI', 'ID', 'WI', 'NM', 'WY', 'IL', 'TX', 'RI', 'MI', 'OR', 'VA', 'SD', 'AL', 'MS', 'MS', 'HI', 'WV', 'WV', 'WV', 'IN', 'NM', 'DE', 'NC', 'NM', 'SC', 'NJ', 'AZ', 'RI', 'SD', 'NH', 'AL', 'WV', 'ID', 'MD', 'IN', 'WY', 'NH', 'MN', 'MA', 'NH', 'MN', 'IA', 'NY', 'AL', 'WV', 'NM', 'CA', 'MA', 'ME', 'FL', 'NH', 'IN', 'WI', 'MA', 'NH', 'TX', 'NC', 'CT', 'NJ', 'WY', 'LA', 'NV', 'WV', 'AR', 'SC', 'KS', 'NY', 'MI', 'MA', 'UT', 'HI', 'PA', 'OR', 'TN', 'CT', 'AZ', 'OR', 'DE', 'MA', 'CT', 'AR', 'SD', 'CT', 'CT', 'MA', 'MS', 'MT', 'AK', 'DE', 'OH', 'MN', 'CA', 'OH', 'NV', 'SC', 'WV', 'NM', 'WY', 'CA', 'KS', 'WY', 'OK', 'UT', 'MA', 'UT', 'MN', 'NE', 'OH', 'KY', 'WA', 'NY', 'IN', 'CO', 'DC', 'AK', 'SC', 'KS', 'UT', 'IL', 'DC', 'DC', 'OK', 'KY', 'NE', 'AL', 'HI', 'SC', 'GA', 'KS', 'PA', 'UT', 'OR', 'ND', 'KY', 'MN', 'OH', 'TX', 'WY', 'GA', 'TX', 'WV', 'NM', 'MI', 'NC', 'NY', 'TX', 'KY', 'SD', 'ID', 'OR', 'WI', 'WV', 'SC', 'CT', 'NV', 'ND', 'MI', 'MT', 'NE', 'UT', 'WV', 'AR', 'MT', 'UT', 'HI', 'KS', 'NY', 'OH', 'HI', 'KS', 'IN', 'OR', 'NY', 'VA', 'MI', 'ID', 'MO', 'AL', 'OR', 'VT', 'AZ', 'VA', 'PA', 'CO', 'KY', 'NJ', 'IL', 'WA', 'WV', 'RI', 'OH', 'MO', 'MD', 'OH', 'VA', 'FL', 'CO', 'NY', 'WV', 'LA', 'MA', 'UT', 'AL', 'ME', 'TX', 'ND', 'CO', 'LA', 'MT', 'OR', 'NH', 'NE', 'WV', 'NV', 'MA', 'MI', 'KY', 'WV', 'KY', 'NJ', 'ME', 'TX', 'MN', 'VA', 'DC', 'MD', 'RI', 'MA', 'MD', 'NM', 'MN', 'MI', 'AZ', 'AL', 'MI', 'SC', 'MS', 'MS', 'CA', 'MD', 'ND', 'IL', 'SD', 'AL', 'NV', 'LA', 'VA', 'DE', 'CT', 'CO', 'MA', 'OR', 'WA', 'SC', 'IN', 'MD', 'NV', 'TX', 'ND', 'WV', 'CO', 'TX', 'FL', 'AL', 'WV', 'MI', 'NY', 'MS', 'MO', 'AR', 'MS', 'NY', 'SD', 'AK', 'WV', 'SC', 'VA', 'MS', 'SD', 'MN', 'AL', 'CO', 'ME', 'GA', 'AZ', 'MA', 'AZ', 'IN', 'DE', 'WI', 'ME', 'DC', 'GA', 'HI', 'VA', 'NY', 'PA', 'AR', 'HI', 'DE', 'WV', 'OK', 'OR', 'ND', 'MO', 'AR', 'GA', 'TN', 'MA', 'ND', 'IA', 'NJ', 'MT', 'AL', 'NY', 'PA', 'VT', 'NC', 'CT', 'MO', 'WV', 'NJ', 'AK', 'LA', 'AL', 'IN', 'MA', 'DE', 'SC', 'NH', 'LA', 'MS', 'NM', 'WA', 'SC', 'MT', 'ME', 'NM', 'AZ', 'CT', 'IL', 'IN', 'AR', 'RI', 'ND', 'NH', 'NV', 'UT', 'NC', 'MI', 'WI', 'AR', 'NH', 'TX', 'ID', 'CT', 'NH', 'WY', 'OR', 'SC', 'MD', 'NY', 'NM', 'LA', 'UT', 'AL', 'DE', 'WV', 'KY', 'NC', 'WV', 'AZ', 'WV', 'ND', 'WA', 'ID', 'CT', 'OK', 'IA', 'NE', 'ID', 'OR', 'SD', 'DE', 'WA', 'CT', 'MN', 'WA', 'PA', 'ID', 'MS', 'WA', 'DC', 'KY', 'OH', 'TN', 'ID', 'WV', 'WI', 'OK', 'WV', 'SD', 'KS', 'NC', 'NY', 'WI', 'SC', 'UT', 'NC', 'IN', 'AR', 'ME', 'NY', 'OR', 'IL', 'MA', 'CT', 'WI', 'OK', 'DE', 'AZ', 'AK', 'MI', 'WA', 'SD', 'SD', 'AK', 'MA', 'AR', 'KS', 'OR', 'NC', 'OK', 'NJ', 'OH', 'NM', 'OH', 'MI', 'KS', 'IL', 'RI', 'AR', 'NY', 'WY', 'NC', 'OR', 'VT', 'SD', 'DC', 'RI', 'ID', 'OK', 'MN', 'WA', 'WV', 'NH', 'WI', 'MD', 'IN', 'IN', 'NY', 'OR', 'OK', 'WI', 'NJ', 'AR', 'UT', 'DC', 'AK', 'AZ', 'KS', 'OH', 'KS', 'SC', 'TN', 'CA', 'MI', 'IN', 'RI', 'MO', 'TN', 'CT', 'ME', 'MD', 'NC', 'SC', 'CA', 'LA', 'WI', 'IL', 'IN', 'AL', 'OK', 'IA', 'VT', 'NY', 'LA', 'SC', 'ID', 'MO', 'ME', 'MS', 'SD', 'OK', 'WY', 'GA', 'VT', 'MD', 'IN', 'WV', 'OH', 'OH', 'SC', 'AZ', 'WV', 'RI', 'CT

In [ ]:
# Si quisieramos convertir main_dict a un objeto DataFrame:
df3 = pd.DataFrame(main_dict)
df3.head()

,State,Account Length,Area Code,Phone,Int'l Plan,VMail Plan,VMail Message,Day Mins,Day Calls,Day Charge,...,Eve Calls,Eve Charge,Night Mins,Night Calls,Night Charge,Intl Mins,Intl Calls,Intl Charge,CustServ Calls,Churn?
0,KS,128,415,382-4657,no,yes,25,265.100000,110,45.070000,...,99,16.780000,244.700000,91,11.010000,10.000000,3,2.700000,1,False.
1,OH,107,415,371-7191,no,yes,26,161.600000,123,27.470000,...,103,16.620000,254.400000,103,11.450000,13.700000,3,3.700000,1,False.
2,NJ,137,415,358-1921,no,no,0,243.400000,114,41.380000,...,110,10.300000,162.600000,104,7.320000,12.200000,5,3.290000,0,False.
3,OH,84,408,375-9999,yes,no,0,299.400000,71,50.900000,...,88,5.260000,196.900000,89,8.860000,6.600000,7,1.780000,2,False.
4,OK,75,415,330-6626,yes,no,0,166.700000,113,28.340000,...,122,12.610000,186.900000,121,8.410000,10.100000,3,2.730000,3,False.

#Lectura y escritura de ficheros

Fijarse en el cambio que se hace en la dirección de `path2`, añadiendo la palabra "Tab", para hacer referencia al tabulado que se hará.

In [ ]:
infile = path2
outfile = "/content/drive/MyDrive/Machine Learning - Python/Datasets - Machine Learning/customer-churn-model/Tab Customer Churn Model.txt"

In [ ]:
with open(infile, "r") as infile1:
  with open(outfile, "w") as outfile1:
    for line in infile1:
      fields = line.strip().split(",")
      outfile1.write("\t".join(fields))
      outfile1.write("\n")

# 'r' es lectura y 'w' es escritura.

In [ ]:
df4 = pd.read_csv(outfile, sep = "\t")
df4.head()

,State,Account Length,Area Code,Phone,Int'l Plan,VMail Plan,VMail Message,Day Mins,Day Calls,Day Charge,...,Eve Calls,Eve Charge,Night Mins,Night Calls,Night Charge,Intl Mins,Intl Calls,Intl Charge,CustServ Calls,Churn?
0,KS,128,415,382-4657,no,yes,25,265.1,110,45.07,...,99,16.78,244.7,91,11.01,10.0,3,2.70,1,False.
1,OH,107,415,371-7191,no,yes,26,161.6,123,27.47,...,103,16.62,254.4,103,11.45,13.7,3,3.70,1,False.
2,NJ,137,415,358-1921,no,no,0,243.4,114,41.38,...,110,10.30,162.6,104,7.32,12.2,5,3.29,0,False.
3,OH,84,408,375-9999,yes,no,0,299.4,71,50.90,...,88,5.26,196.9,89,8.86,6.6,7,1.78,2,False.
4,OK,75,415,330-6626,yes,no,0,166.7,113,28.34,...,122,12.61,186.9,121,8.41,10.1,3,2.73,3,False.

In [ ]:
print(data3)

<_io.TextIOWrapper name='/content/drive/MyDrive/Machine Learning - Python/Datasets - Machine Learning/customer-churn-model/Customer Churn Model.txt' mode='r' encoding='UTF-8'>

In [ ]:
data3.close()

#Leer datos desde una URL

In [ ]:
medals_url = "http://winterolympicsmedals.com/medals.csv"

In [ ]:
medals_data = pd.read_csv(medals_url, sep = '\t')

In [ ]:
medals_data.head()

                                     <!doctype html>
0  <html data-adblockkey="MFwwDQYJKoZIhvcNAQEBBQA...
1                                             <head>
2                             <meta charset="utf-8">
3      <meta name="viewport" content="width=devic...
4      <link rel="icon" href="data:image/png;base...

#Ficheros de tipo XLS y XLSX

In [ ]:
excel_path1 = "/content/drive/MyDrive/Machine Learning - Python/Datasets - Machine Learning/titanic/titanic3.xls"
excel_path2 = "/content/drive/MyDrive/Machine Learning - Python/Datasets - Machine Learning/titanic/titanic3.xlsx"

Para poder leer un documento excel, hay que especificar la pestaña, en este caso `"titanic3"`.

In [235]:
excel_data1 = pd.read_excel(excel_path1, "titanic3")

In [236]:
excel_data1.head()

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
1,1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1,0,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"

Veamos como poder hacer conversiones a formatos distintos:

In [ ]:
# Consultar en el otro excel del tema 1.

In [237]:
excel_data2 = pd.read_excel(excel_path2, "titanic3")

In [238]:
excel_data2.head()

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
1,1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1,0,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"