# K Nearest Neighbors

In [1]:
import numpy as np
from sklearn import preprocessing, neighbors
from sklearn. model_selection import cross_val_score
from sklearn. model_selection import train_test_split
import pandas as pd

In [2]:
df = pd.read_csv("/content/drive/MyDrive/Machine Learning - Python/Datasets - Machine Learning/cancer/breast-cancer-wisconsin.data.txt")

In [3]:
# Veamos un problema con el header:
df.head()

   1000025  5   1  1.1  1.2  2 1.3  3  1.4  1.5  2.1
0  1002945  5   4    4    5  7  10  3    2    1    2
1  1015425  3   1    1    1  2   2  3    1    1    2
2  1016277  6   8    8    1  3   4  3    7    1    2
3  1017023  4   1    1    3  2   1  3    1    1    2
4  1017122  8  10   10    8  7  10  9    7    1    4

In [4]:
# Solucuón al problema con el header:
df = pd.read_csv("/content/drive/MyDrive/Machine Learning - Python/Datasets - Machine Learning/cancer/breast-cancer-wisconsin.data.txt", header = None)

In [5]:
# Verificamos:
df.head()

        0   1   2   3   4   5   6   7   8   9   10
0  1000025   5   1   1   1   2   1   3   1   1   2
1  1002945   5   4   4   5   7  10   3   2   1   2
2  1015425   3   1   1   1   2   2   3   1   1   2
3  1016277   6   8   8   1   3   4   3   7   1   2
4  1017023   4   1   1   3   2   1   3   1   1   2

In [6]:
# Hay problemas con el tipo de dato en X. De vez en cuando aparece '?' cuando se desconoce una observación.

df.replace('?', -999999.99, inplace = True)

In [7]:
df.describe()

,0,1,2,3,4,5,7,8,9,10
count,6.990000e+02,699.000000,699.000000,699.000000,699.000000,699.000000,699.000000,699.000000,699.000000,699.000000
mean,1.071704e+06,4.417740,3.134478,3.207439,2.806867,3.216023,3.437768,2.866953,1.589413,2.689557
std,6.170957e+05,2.815741,3.051459,2.971913,2.855379,2.214300,2.438364,3.053634,1.715078,0.951273
min,6.163400e+04,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,2.000000
25%,8.706885e+05,2.000000,1.000000,1.000000,1.000000,2.000000,2.000000,1.000000,1.000000,2.000000
50%,1.171710e+06,4.000000,1.000000,1.000000,1.000000,2.000000,3.000000,1.000000,1.000000,2.000000
75%,1.238298e+06,6.000000,5.000000,5.000000,4.000000,4.000000,5.000000,4.000000,1.000000,4.000000
max,1.345435e+07,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,4.000000

In [8]:
df.columns = ['Id', 'v1', 'v2', 'v3', 'v4', 'v5', 'v6', 'v7', 'v8', 'v9', 'class']

In [9]:
df.head()

        Id  v1  v2  v3  v4  v5  v6  v7  v8  v9  class
0  1000025   5   1   1   1   2   1   3   1   1      2
1  1002945   5   4   4   5   7  10   3   2   1      2
2  1015425   3   1   1   1   2   2   3   1   1      2
3  1016277   6   8   8   1   3   4   3   7   1      2
4  1017023   4   1   1   3   2   1   3   1   1      2

In [10]:
Y = df['class']
X = df[['v1', 'v2', 'v3', 'v4', 'v5', 'v6', 'v7', 'v8', 'v9']]

In [11]:
Y.head()

0    2
1    2
2    2
3    2
4    2
Name: class, dtype: int64

In [12]:
X.head()

   v1  v2  v3  v4  v5  v6  v7  v8  v9
0   5   1   1   1   2   1   3   1   1
1   5   4   4   5   7  10   3   2   1
2   3   1   1   1   2   2   3   1   1
3   6   8   8   1   3   4   3   7   1
4   4   1   1   3   2   1   3   1   1

In [13]:
Y

0      2
1      2
2      2
3      2
4      2
      ..
694    2
695    2
696    4
697    4
698    4
Name: class, Length: 699, dtype: int64

In [14]:
X

     v1  v2  v3  v4  v5  v6  v7  v8  v9
0     5   1   1   1   2   1   3   1   1
1     5   4   4   5   7  10   3   2   1
2     3   1   1   1   2   2   3   1   1
3     6   8   8   1   3   4   3   7   1
4     4   1   1   3   2   1   3   1   1
..   ..  ..  ..  ..  ..  ..  ..  ..  ..
694   3   1   1   1   3   2   1   1   1
695   2   1   1   1   2   1   1   1   1
696   5  10  10   3   7   3   8  10   2
697   4   8   6   4   3   4  10   6   1
698   4   8   8   5   4   5  10   4   1

[699 rows x 9 columns]

# Clasificador de los K vecinos más cercanos

In [15]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2)

In [16]:
# clasificador = clf

clf = neighbors.KNeighborsClassifier()

In [17]:
clf.fit(X_train, Y_train)

KNeighborsClassifier()

In [18]:
accuracy = clf.score(X_test, Y_test)
accuracy

0.9571428571428572

# Clasificando nuevos datos

In [19]:
# Datos biométricos de una persona

observation_1 = np.array([4,2,1,1,1,2,3,2,1])

In [20]:
clf.predict(observation_1)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(

ValueError: ignored

In [21]:
# Redefinimos observation_1, siguiendo la sugerencia en la descripción de error anterior.

observation_1 = observation_1 = np.array([4,2,1,1,1,2,3,2,1]).reshape(1,-1)

In [22]:
clf.predict(observation_1)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(

array([2])

In [23]:
# Ahora, los datos de dos personas.

observation_2 = np.array([[4,2,1,1,1,2,3,2,1],[4,1,2,2,1,3,2,1,2]]).reshape(2,-1)

In [24]:
clf.predict(observation_2)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(

array([2, 2])